name: New Release (Manual Trigger)

on:
  workflow_dispatch:
  # Triggered by the Plugin Repos
  repository_dispatch:
    types: [ plugin-update ]

permissions:
  contents: read
  pull-requests: write

jobs:
  release:
    uses: openkcm/build/.github/workflows/release.manual.yaml@fix/release-process
    secrets: inherit

